(defpackage :logos.grant-cardone (:use :cl))
(in-package :logos.grant-cardone)

(defvar *current-quality* -1)
(defvar qualities-of-the-successful
  '((have a can do attitude)
    (believe that i can figure it out)
    (focus on opprotunity)
    (love challenges)
    (seek to solve problems)
    (persist until success)
    (take risk)
    (be unreasonable)
    (be dangerous)
    (create wealth)
    (readily take action)
    (always say yes (i dont agree with this one))
    (habitually commit)
    (go all the way)
    (focus on the now)
    (demonstrate courage)
    (embrace change)
    (determine and take the right approach)
    (break traditional ideas)
    (be goal oriented)
    (be on a mission)
    (have a high level of motivation)
    (be interested in results)
    (have big goals)
    (create your own reality (ie in the limit - a reality distortion field))
    (commit first - figure it out later)
    (be highly ethical)
    (be interested in the group)
    (continously learn)
    (be uncomfortable)
    (reach up and out in relationships)
    (be disciplined)))

(defun next-quality-of-success ()
  (setf *current-quality*
        (mod (+ *current-quality* 1)
           (length qualities-of-the-successful)))
  (elt qualities-of-the-successful *current-quality*))
