(in-package :logos)
(defun make-coffee ()
  '((purpose (prepare the mind stimulate
              that will invigorate my thoughts and action))
    (mantra ((im grateful for what is done)
             (i gaze at the white slate ahead)
             (my will is strong)
             (my vigor renewed)
             (my vision is clear)
             (sally forth)))
   (movement ((throw-away old filter)
              (put new filter in)
              (measure out grounds (smelling with intent))
              (fill coffee pot with water)
              (pour water into maker (observing clearness of water))
              (flick switch)))
   (mental-states ((gratitude)
                   (dexterous power (as if mere finger flicks have power to move mountians))
                   (heart foritification (as if breathing spirit into the heart))
                   (breath into 3rd eye (holding heart energy))
                   (3rd eye activation only (moving heart energy into eye))
                   (outpouring of all energies)))))
